name: Docker Image CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          TEAMCITY_VERSION: 2024.12-linux-sudo
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: since2006/teamcity-agent:${{ env.TEAMCITY_VERSION }}-java8
          build-args: |
            TEAMCITY_VERSION=${{ env.TEAMCITY_VERSION }}
            jdkLinuxComponent=https://corretto.aws/downloads/resources/8.432.06.1/amazon-corretto-8.432.06.1-linux-x64.tar.gz
            jdkLinuxComponentMD5SUM=6fb237cb31a9c4474bf5f79798d94943
